### ISSUE TITLE
Exception: no converter string

### ISSUE THREAD

**Issue by ftpronk** [OpenMS/autowrap#12]
I'm trying to wrap a c++  code containing some std::string.  After creating a .pxd file, and running autowrap, I get the error here-below.  Would you have any hints on how to solve it?  I included "from libcpp.string cimport string" at the top of my pxd file.

Traceback (most recent call last):
  File "/home/ftpronk/local/bin/autowrap", line 9, in <module>
    load_entry_point('autowrap==0.5.1', 'console_scripts', 'autowrap')()
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/Main.py", line 67, in main
    _main(sys.argv[1:])
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/Main.py", line 121, in _main
    run(pxds, addons, converters, out)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/Main.py", line 202, in run
    extra_opts)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/Main.py", line 190, in create_wrapper_code
    inc_dirs = autowrap.generate_code(decls, instance_map, out, False, manual_code, cimports)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/__init__.py", line 63, in generate_code
    gen.create_pyx_file(debug)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/CodeGenerator.py", line 171, in create_pyx_file
    create_for(ResolvedClass, self.create_wrapper_for_class)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/CodeGenerator.py", line 167, in create_for
    method(resolved)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/CodeGenerator.py", line 300, in create_wrapper_for_class
    codes = self.create_wrapper_for_method(r_class, name, methods)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/CodeGenerator.py", line 412, in create_wrapper_for_method
    code = self.create_wrapper_for_nonoverloaded_method(cdcl, py_name, methods[0])
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/CodeGenerator.py", line 562, in create_wrapper_for_nonoverloaded_method
    out_converter = self.cr.get(res_t)
  File "/home/ftpronk/local/lib/python2.7/site-packages/autowrap-0.5.1-py2.7.egg/autowrap/ConversionProvider.py", line 116, in get
    raise Exception("no converter for %s" % cpp_type)
Exception: no converter for string

**Comment by Eliasvan** [comment]
Still doesn't work with version 0.6.0 of Feb 9, 2015,
workaround is to use:

    from libcpp.string cimport string as libcpp_string

in your `.pxd`-file, and then use `libcpp_string` instead of `string`.

**Comment by david-cliqz** [comment]
@Eliasvan I get the same error even if I import `libcpp.string`.

**Comment by uweschmitt** [comment]
Can you provide a simple file for reproduction ?

**Comment by scganterh** [comment]
Hi @uweschmitt, I am facing the same issue. Here is my (very simple) `.pxd` file:

    from libcpp.string cimport string
    
    
    cdef:
        extern from "a_api.h" namespace "a_api":
            cppclass A:
                string get_string()

            A& get_object(unsigned int index)

I hope this helps. If you need more information just let me know.

**Comment by uweschmitt** [comment]
@scganterh can you try to use `from libcpp.string cimport string as libcpp_string` instead ? It is hard coded in `autowrap` to use `libcpp_string` to map  _C++_ and _Pythone_ strings.

**Comment by cganterh** [comment]
Yes, that works. (I'm responding from an other account)

Isn't that behavior unexpected?

**Comment by jpfeuffer** [comment]
It is a bit unexpected, I agree. But it is less prone to clashes with user-defined string classes.
