### ISSUE TITLE
CFuncDeclaratorNode  AttributeError

### ISSUE THREAD

**Issue by skoudoro** [OpenMS/autowrap#148]
Hello autowrap Team,

I tried to generate the `pyc` file of this [pxd file](https://gist.github.com/skoudoro/64923d0f089d9128c72fb9fb75fb7473) and I encounter the following issues.

Can I avoid those issues via the directives? Any advice to make it work is welcomed! 

Thank you in advance for your feedback.

```python
Traceback (most recent call last):
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/bin/autowrap", line 8, in <module>
    sys.exit(main())
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 67, in main
    _main(sys.argv[1:])
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 121, in _main
    run(pxds, addons, converters, out)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 216, in run
    decls, instance_map = autowrap.parse(pxds, ".")
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/__init__.py", line 52, in parse
    return DeclResolver.resolve_decls_from_files(files, root, num_processes, cython_warn_level)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 246, in resolve_decls_from_files
    return resolve_decls_from_files_single_thread(pathes, root, cython_warn_level)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 239, in resolve_decls_from_files_single_thread
    decls.extend(PXDParser.parse_pxd_file(full_path, cython_warn_level))
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 591, in parse_pxd_file
    result.append(handler(body, lines, path))
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 279, in parseTree
    print(decl.base.name)
AttributeError: 'CFuncDeclaratorNode' object has no attribute 'name'
```

and 

```python
Traceback (most recent call last):
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/bin/autowrap", line 8, in <module>
    sys.exit(main())
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 67, in main
    _main(sys.argv[1:])
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 121, in _main
    run(pxds, addons, converters, out)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/Main.py", line 216, in run
    decls, instance_map = autowrap.parse(pxds, ".")
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/__init__.py", line 52, in parse
    return DeclResolver.resolve_decls_from_files(files, root, num_processes, cython_warn_level)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 246, in resolve_decls_from_files
    return resolve_decls_from_files_single_thread(pathes, root, cython_warn_level)
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 239, in resolve_decls_from_files_single_thread
    decls.extend(PXDParser.parse_pxd_file(full_path, cython_warn_level))
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 596, in parse_pxd_file
    result.append(handler(body, lines, path))
  File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 494, in parseTree
    raise Exception("multi ptr not supported")
Exception: multi ptr not supported
```

**Comment by jpfeuffer** [comment]
Hi, unfortunately, both function pointers and pointers of pointers are both not supported by autowrap.
How would you want to expose that to Python?
In general, I think for wrapping such low-level functions, we would need your support if you want to go forward with autowrap since this is out of the use-cases we are dealing with and we do not have much experience with.

**Comment by skoudoro** [comment]
ok, thank you for the feedback, so, for now:

- I will add  `# wrap-ignore`
- Then I will try to find a way to automate a workaround as a preprocessing.

**Comment by jpfeuffer** [comment]
Yes exactly. I also would ignore the wrapping for now and reevaluate if those functions/classes are really needed in the python interface.

In theory one could probably pass some kind of long int or something instead of pointers but this is very unpythonic and autowrap is currently more focussed on memory safety instead of speed in the glue code it generates.

In your case you even have pointer to char pointers/arrays. Maybe it would make sense to provide glueing functions on the C(++) side that take std::strings instead (if that is what they represent)?

For passing function pointers, one should maybe reevaluate if this low-level interface is needed at all in python.

**Comment by skoudoro** [comment]
For pointer function, did you consider following the callback demo from cython: https://github.com/cython/cython/tree/master/Demos/callback

ps: sorry for the naive question

**Comment by jpfeuffer** [comment]
No, I have not seen this yet. I bet it was not considered yet.
As always it should work if you wrap-ignore it and provide your own pyx addon code.

But here, one could even think about adding a new directive to autogenerate the python function and the callback wrapper that converts the inputs from python to C. One would need to specify which parameter specifies the data for which callback function. E.g. in
`void find_cheeses(cheesefunc user_func, void *user_data)` one needs to know, that user_data is passed to user_func, if multiple callback functions or other parameters are allowed in the function.
First, we need to check if we can even parse the ctypedef of a function pointer correctly into our internal data structures (which are mainly for classes and enums). This would be needed for type information and to choose the correct conversion in the autowrapped callback function.
