### ISSUE TITLE
[autowrap 0.6.1] multiple types of annotations for a class not supported

### ISSUE THREAD

**Issue by Eliasvan** [OpenMS/autowrap#29]
Tested with commit d0e9a5 (Feb 9, 2015).
Tested by using both "wrap-inherits" and "wrap-instances" annotations together:
Only the first declared annotation is executed.

Test code:

```
cdef extern from "<gtsam/geometry/Pose2.h>" namespace "gtsam":
    cdef cppclass Pose2:
        Pose2()

cdef extern from "<gtsam/nonlinear/NonlinearFactor.h>" namespace "gtsam":
    cdef cppclass NoiseModelFactor1[VALUE]:
        void print_ "print"()

cdef extern from "<gtsam/slam/PriorFactor.h>" namespace "gtsam":
    cdef cppclass PriorFactor[VALUE](NoiseModelFactor1[VALUE]):
        # wrap-inherits:
        #   NoiseModelFactor1[VALUE]
        # wrap-instances:
        #   PriorFactor_Pose2 := PriorFactor[Pose2]
        PriorFactor()
```

In this case, the following error is returned:

```
Traceback (most recent call last):
File "./setup.py", line 41, in <module>
    main()
File "./setup.py", line 30, in main
    autowrap_main(args)
File "/usr/lib/python2.7/site-packages/autowrap/Main.py", line 121, in _main
    run(pxds, addons, converters, out)
File "/usr/lib/python2.7/site-packages/autowrap/Main.py", line 202, in run
    extra_opts)
File "/usr/lib/python2.7/site-packages/autowrap/Main.py", line 190, in create_wrapper_code
    inc_dirs = autowrap.generate_code(decls, instance_map, out, False, manual_code, cimports)
File "/usr/lib/python2.7/site-packages/autowrap/__init__.py", line 63, in generate_code
    gen.create_pyx_file(debug)
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 165, in create_pyx_file
    create_for(ResolvedClass, self.create_wrapper_for_class)
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 161, in create_for
    method(resolved)
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 294, in create_wrapper_for_class
    codes = self.create_wrapper_for_method(r_class, name, methods)
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 420, in create_wrapper_for_method
    method,
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 548, in create_wrapper_for_nonoverloaded_method
    method)
File "/usr/lib/python2.7/site-packages/autowrap/CodeGenerator.py", line 448, in _create_fun_decl_and_input_conversion
    converter = self.cr.get(t)
File "/usr/lib/python2.7/site-packages/autowrap/ConversionProvider.py", line 117, in get
    raise Exception("no converter for %s" % cpp_type)
Exception: no converter for shared_ptr[PriorFactor[Pose2]] &
```

If I would swap the annotations, such that the last method is defined as:

```
cdef extern from "<gtsam/slam/PriorFactor.h>" namespace "gtsam":
    cdef cppclass PriorFactor[VALUE](NoiseModelFactor1[VALUE]):
        # wrap-instances:
        #   PriorFactor_Pose2 := PriorFactor[Pose2]
        # wrap-inherits:
        #   NoiseModelFactor1[VALUE]
        PriorFactor()
```

then the wrapping will give no errors, but the "print_()" method will not be inherited.

**Comment by uweschmitt** [comment]
`wrap-inherit` is broken because Cython is broken for this. The issue is open for a longer time now...

You have to declare the inherited methods again.

**Comment by Eliasvan** [comment]
Thanks for your quick reply!
The solution you suggested is indeed the one I'm using for now.

Strange thing is that "wrap-inherits" **does** work if there is no "wrap-instances" defined.
Is this because Cython only supports non-templated classes to inherit from other classes (or classes to inherit from non-templated classes)?

**Comment by jpfeuffer** [comment]
I just added a test for something like this. seems to work now.
